Document: cyassl
Title: Debian cyassl Manual
Author: <insert document author here>
Abstract: This manual describes what cyassl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cyassl/cyassl.sgml.gz

Format: postscript
Files: /usr/share/doc/cyassl/cyassl.ps.gz

Format: text
Files: /usr/share/doc/cyassl/cyassl.text.gz

Format: HTML
Index: /usr/share/doc/cyassl/html/index.html
Files: /usr/share/doc/cyassl/html/*.html
